// <auto-generated />
namespace WypasionaKsiegarniaMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class baza_kategoriefinale232 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(baza_kategoriefinale232));
        
        string IMigrationMetadata.Id
        {
            get { return "201601232308175_baza_kategoriefinale232"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
